### ISSUE TITLE
Possibility to integrate Rust Cassandra client into PHP

### ISSUE THREAD

**Issue by dbalabka** [wasmerio/php-ext-wasm#86]
Hello,

Recently, I have faced a problem that official [PHP Cassandra Client](https://pecl.php.net/package/cassandra) isn't maintained well and does not support PHP >=7.3. The idea might sound crazy but still. Is it possible to compile https://crates.io/crates/cdrs into WASM binary, use inside PHP and rely on such client on production? Also, what is the cost and limitations of using `php-ext-wasm`?

Thanks in advance!

**Comment by Hywan** [comment]
The idea isn't crazy. You need WASI support so that you will have access to the network and I/O stack. We have been working on it very recently, and it will come in the next release of `php-ext-wasm`.

**Comment by dbalabka** [comment]
@Hywan thank you for an answer. Currently, I am reviewing two options:
1. Compile Rust client into WASM 
2. or connect it with PHP FFI. 

Am I'm right that WASM extension has it own some FFI layer to convert types? Not sure, but I guess native PHP FFI might bring better performance. Am I wrong?

**Comment by Hywan** [comment]
WebAssembly has WASI (System Interfaces), which is “similar” to FFI (in terms of goals, it has many differences though, check https://hacks.mozilla.org/2019/03/standardizing-wasi-a-webassembly-system-interface/ to learn more).

I'm not sure PHP FFI will bring better performance. I'm going to update the extension to Wasmer 0.10 so that we will have WASI support
